# Generated by Django 3.2.8 on 2021-10-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalprice',
            new_name='price',
        ),
    ]
